Tried Implenting Verification functions.
TheDexter25/Insurance-management-system pull request #2
Opened 2023-06-28 04:55 UTC by TheDexter25

-Changed string variables to long for phone numbers and policyNumbers
-Implemented a new class called Verification
-Implemented a new function for verifying Phone number as input as well as PolicyNumber as input
-Tried Implementing the function to check whether input is 10 digit or not

2023-06-28 04:56 UTC, TheDexter25 commented
test comment

2023-06-30 12:53 UTC, prajyot-w commented on src/com/company/Verification.java
> +       sc.nextLine();
Seems like here, we are just validating if we have any input and if that input is a number. Here, we also need to verify that the number entered is 10 digit long or not.

2023-06-30 12:54 UTC, prajyot-w requested changes
Seems like validation of input is invalid !

2023-07-05 14:53 UTC, prajyot-w approved these changes

2023-07-05 15:11 UTC, merged